privacybydesign/irmago

- credinfo.go
- irmaclient/client.go
- irmaclient/credential.go
- irmaclient/irmaclient_test.go
- irmaclient/keyshare.go
- irmaclient/logs.go
- irmaclient/session.go
- irmaclient/session_test.go
- irmaclient/storage.go
- irmaclient/updates.go
- irmaconfig.go
- irmameta/irmameta.go
- schememgr/cmd/keygen.go
- schememgr/cmd/sign.go
- schememgr/cmd/verify.go
- schememgr/main.go
- transport.go
This prevents the 'use of internal package not allowed' go compile error
> Rename 'credentials/irmago' to 'privacybydesign/irmago'

- irmaclient/logs.go
- irmaclient/manual_session_test.go
- irmaclient/session.go
- irmaclient/session_test.go
- messages.go
This PR adds support for handling manual signature session (i.e. session started with a signature request blob, without using the IRMA API server).
Manual signature requests can be created with the [IRMA Signature App](https://github.com/privacybydesign/irma_signature_app).
> Manual sigrequests

- irmaconfig.go
Fixed bug where windows path seperators caused ReadAuthenticatedFile to fail looking up a file in the index.
> Bugfix reading configuration on windows

- attributes.go
- irmaclient/irmaclient_test.go
Simple fix to stop Map from crashing on credentials that have too few attributes for their type.
> Fix crashing on credentials that are too short.

- irma/cmd/session.go
This makes sure that irma session never complains about attributes that might not be in the local version of the schemes, but are in the global one.
> Changed irma session command to run updateschemes when starting.

- irma/cmd/session.go
When no network interfaces are available, for example because the pc is in airplane mode, the `irma` tool gives a nil pointer reference. This fix solves this issue.
> Fix for nil pointer dereference when not having network interfaces

- descriptions.go
- irmaconfig.go
- requests.go
- server/api.go
This pull request adds irmago support for deprecation tags in schemes. With these tags issuers and credentials can be deprecated without having to remove the data from the scheme. This can be done by adding a `DeprecatedSince` tag to an issuer or credential with the time of deprecation in it, i.e.
```<DeprecatedSince>1571903161</DeprecatedSince>```
This is needed to remove public key expiry warnings of deprecated keys by `irma scheme verify` and in the future potentially for deprecation warnings on the [attribute index page](https://privacybydesign.foundation/attribute-index/en/).
> Deprecation tags

- irmaclient/session.go
- messages.go
When a user is doing a session and he has no keyshare enrollment, the current behaviour is that both a `KeyshareEnrollmentMissing` and a `Failure` event are being generated. In the end this makes that in the IRMA app the nice 'user has no account' error screen is being overrulled by a failure and an exception report.
This pull request introduces a new boolean in `SessionError` to communicate that an error already has been handled in a nice way. In this way the fail function knows it does not have to send its 'an unexpected error occurred' failure.
> Fix for keyshare enrollment missing error being overruled by failure

- attributes.go
- internal/sessiontest/handlers_test.go
- internal/sessiontest/session_test.go
- irmaclient/client.go
When a credential expires that is not singleton (let's say that `pbdf.pbdf.mobilenumber` has expired) and the user refreshes/gets re-issued this credential, the current behaviour is that a new `mobilenumber` credential is added and the old, expired one is still present in the user's wallet. This means the user has to manually remove this old credential. This is not very user-friendly.
This PR proposes to delete previous credentials, when adding a new credential with exactly the same attribute values as the old one. Only expiry date and issuance time are ignored, because it is logical that these dates might differ over multiple issuance sessions. When differences are detected, nothing is done (for example because the user added another mobile number or because the issuer changed the numer …
> Non singleton refresh

- irma/cmd/session.go
- server/irmad/cmd/root.go
When using the option `--url` the port does not have to be specified explicitly, it is filled in the url by irma server/irma session such that it corresponds with the `--port` value. To use this feature the port must be specified in the url as `:port`. For example specify `--url http://localhost:port --port 1234` instead of `--url http://localhost:1234 --port 1234`. I added this in the --help.
> Added docs for variable port in --url to --help

- identifiers.go
- internal/servercore/api.go
- internal/servercore/helpers.go
- internal/sessiontest/session_test.go
- irmaconfig.go
- messages.go
- requests.go
This should fix the unclear server responses when non-optional attributes are missing.
For this purpose we made a distinction between identifiers from the request that are not in the configuration and vice versa. This way, we can display different error messages where necessary.
I could add an extra test case in which it actually sends a request with non-optional attributes missing, since it currently only tests if it updates after calling `Download`.
> Non optional attribute missing

- internal/fs/fs.go
- irma/cmd/sign.go
- irmaconfig.go
When having symlinks in your irma_configuration folder leaded to errors while verifying and signing. For `irma scheme verify` this was already fixed in [commit 6048c42](https://github.com/privacybydesign/irmago/commit/6048c42ef2541c870b9c9569fd23282bb5578d75). This fix extends this solution to also use this when doing `irma scheme sign`.
> Use verify filepath.Walk symlink fix also for sign

- attributes.go
This pull request should fix the error why in the new `irmamobile` app the logs sometimes stop loading more logs.
> Fix: calculate expiry date using signing date instead of current date

- requests.go
Validation of disclosure requests now checks that the disclosure contains any attributes. This means that the server does not accept such requests. On the client side, this enforces that such a request is not even sent.
> fix: check that disclosure is empty

- irmaclient/session.go
This change is done since the rebadge did not provide sufficient value, as
rebadged errors are already recognizable enough on their own.
Fixes https://gitlab.science.ru.nl/irma/irmamobile/-/issues/414
> KeyshareError no longer rebadges existing sessionerrors to ErrorKeyshare

- irma/cmd/sign.go
If a text file in a scheme has CRLF line endings, the following error is now emitted:
```
[2021-02-05T15:55:18+01:00] ERROR Failed to sign scheme: Failed to calculate file index: irma-demo/description.xml contains CRLF (Windows) line endings, please convert to LF
exit status 1
```
> Force Unix (LF) line endings in schemes during irma scheme sign

- server/api.go
Fixes a bug that caused the callback to indicate content type of the request body as text even when no jwt key was installed in the server.
> Ensure callback body content type is json for json messages.

- server/conf.go
When checking the static sessions configuration, the JWT keys need to be loaded. Otherwise, the `conf.JwtRSAPrivateKey == nil` check will always fail.
> Fix: static sessions cannot be loaded when AllowUnsignedCallbacks is disabled

- descriptions.go
- schemes.go
For consistency, we also store the LogoPath in a separate field for `RequestorInfo`, just like we did for wizards (PR #118).
> Create separate LogoPath field in RequestorInfo for file path

- verify.go
> correctly decode randomblind attributes in IRMA server

- internal/sessiontest/legacy_test.go
- internal/sessiontest/main_test.go
- internal/sessiontest/session_test.go
- irma/cmd/session.go
- irmaclient/irmaclient_test.go
- irmaclient/session.go
- messages.go
- requests.go
- server/api.go
- server/irmac/irmac.go
- server/irmaserver/api.go
- server/irmaserver/handle.go
- server/irmaserver/helpers.go
- server/irmaserver/sessions.go
- server/requestorserver/server.go
- wait_status.go
* Adds new `/irma/frontend/status` and `/irma/frontend/statusevents` endpoints which returns the session status as well as the session pointer to the next session, if applicable
* Instead of an `irma.FrontendAuthorization`, the `StartSession()` function of the `irmaserver` library and the `POST /session` endpoint of the `irma server` now return a new struct, `FrontendSessionRequest`, which contains all data relevant to the frontend:
* the frontend authorization token
* new minimum and maximum protocol versions indicating to the frontend the availability of the new status endpoints
* the `PairingRecommended` which was previously included in `irma.Qr`
> Shoulder surf chained sessions

- attributes.go
- go.mod
- go.sum
- irma/cmd/genkeypair.go
- irma/cmd/issuer-keygen.go
- irma/cmd/issuer-keyprove.go
- irma/cmd/issuer-keyverify.go
- irma/cmd/meta.go
- irma/cmd/revocation-keypair.go
- irmaclient/client.go
- irmaclient/irmaclient_test.go
- irmaclient/keyshare.go
- irmaconfig.go
- irmago_test.go
- keyring.go
- revocation.go
- server/conf.go
- server/irmaserver/helpers.go
- server/requestorserver/conf.go
- verify.go
Additionally:
* `gabi.PublicKey`, `gabi.PrivateKey` and related methods moved to `gabikeys`
* handle additional errors returned by gabi
> Bump gabi to rangeproof supporting version

- server/irmaserver/sessions.go
- server/irmaserver/sessions_test.go
When periodically iterating over sessions to see if they need to be expired,
the `memorySessionStore.deleteExpired()` method of the IRMA server locks the
session store mutex, and while that is locked it additionally locks each
session mutex when handling it. If a session is currently being handled by an
endpoint which also locks the session mutex, `deleteExpired()` therefore has to
wait for the handler to finish dealing with the session. However, when that
session attempts to starts a new session (as part of a session chain), it tries
to lock the session store mutex again, which was already locked: a deadlock.
We solve this by making `deleteExired()` not request a session lock while the
entire store is also locked: the store and session locking are now done
sequentially. That way, even …
> Prevent possible mutex deadlock when using chained sessions

- keyring.go
This solves the following. If:
- an issuer exists in the scheme whose identifier is of the form $scheme.$issuer$suffix,
where $scheme.$issuer is another existing issuer in the scheme,
- issuer $scheme.$issuer$suffix has a private key installed in the --privkeys folder,
Then the IRMA server refused to startup with an incorrect error message
("Private key 0 of issuer $scheme.$issuer does not belong to corresponding public key").
> Fix private key issue of issuer if another issuer with a similar name exists

- README.md
- docker-compose.yml
- internal/test/postgres.go
- server/keyshare/myirmaserver/conf_email_test.go
Added a `docker-compose` file such that we can run all unit tests without having to install external packages manually.
> Added docker-compose file to run unit tests

- irma/cmd/keyshare-server.go
- server/keyshare/keyshareserver/postgresdb.go
This PR contains two keyshare server fixes:
* During configuration of the keyshare server `storage_primary_keyfile` was retrieved which should be `storage_primary_key_file`
* When too many wrong PINs are entered, the initial backoff is now set to 60 seconds like the current keyshare server. This is also required by the `irmamobile` integration tests which expect 60 and not 30 seconds.
> Keyshare server fixes

- server/irmaserver/api.go
This makes the error emitted in this case the same as that of the /statusevents endpoint used by the frontend.
> Fix enormous stacktrace in stdout when SSE is disabled and requestor /statusevents endpoint is invoked

- server/irmaserver/sessions_test.go
This should fix the GitHub Action status check, being introduced in #184, to download the issuer schemes on every run. This saves time and it reduces load on the production environment.
Test:
Run `docker-compose run test -v ./...` and verify that there is no test anymore that takes an unexpectedly long time.
> Fix: prevent unit tests from downloading default schemes

- server/irmaserver/api.go
Fix for little mistake where `ineffassign` complains about. Due to that the GitHub Action of #184 does not succeed anymore.
> Fix: make sure updateAndUnlock never ignores given error

- .github/workflows/status-checks.yml
- .github/workflows/weekly-checks.yml
`golint` is not included on purpose, because we have too many issues there still.
For the time being, the status checks also don't run `gocylco` (for code complexity). The configuration of that is a bit more complex, because we have to only check the diff here, and I was not able to get that fully right. In some cases some code complexity might be unavoidable, so it might also be good to add output the `gocyclo` output to a PR review, such that it can be manually judged. This is possible, but requires some additional configuration too.
> Added Github action for linter

- irma/cmd/request.go
- irma/cmd/session.go
- wait_status.go
Useful for testing [static QRs](https://irma.app/docs/irma-server/#static-irma-qrs) and to handle sessions for the UniqueID issuer.
irma session --url $URL --static mystaticsession
irma session --from-package $(curl "https://angrygames.nl/start_session.php?type=18plus") --pairing
> Feat: added option for static sessions and session packages to irma session command

- internal/sessiontest/revocation_test.go
Fix for the following test failure:
```
=== RUN   TestRevocationAll
--- FAIL: TestRevocationAll (0.30s)
=== RUN   TestRevocationAll/Cache
revocation_test.go:591: 
Error Trace:	revocation_test.go:591
Error:      	Not equal: 
expected: "max-age=60"
actual  : "max-age=59"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-max-age=60
+max-age=59
Test:       	TestRevocationAll/Cache
--- FAIL: TestRevocationAll/Cache (0.30s)
Expected :max-age=60
Actual   :max-age=59
```
It happens when the test hits a time change while running (so the clock changes from 12h00m00s to 12h00m01s. This happens quite regularly due to small network delays.
> Fix: TestRevocationAll/Cache test should take into account network delay

- .github/workflows/weekly-checks.yml
Can be useful when you want to test the `Dockerfile` when making changes.
> Chore: make it possible to trigger weekly checks manually

- go.mod
- go.sum
Apply fix https://github.com/alexandrevicenzi/go-sse/issues/8
Causes issues at the UniqueID-issuer where the IRMA server library is used in combination with `go-chi` middleware.
> Fix: go-sse cannot be used in combination with go-chi middleware

- internal/sessiontest/helper_dosession_test.go
- internal/sessiontest/helper_servers_test.go
- internal/sessiontest/session_test.go
- server/api.go
- server/irmaserver/api.go
- server/irmaserver/sessions.go
- server/keyshare/keyshareserver/server.go
- server/keyshare/myirmaserver/server.go
- server/requestorserver/server.go
If the next session URL responds so slowly that a polling lands in the middle, then:
1) the poll HTTP handler locks the session store, and first tries to lock the session before unlocking the session store;
2) the /proofs HTTP handler has the session locked, and tries locking the session store when the next session URL finally responds. But 1) still has the sessionstore lock, so 2) cannot complete and unlock the session lock, so 1) cannot complete and release the session store lock. Deadlock.
The fix is to make the unlocking of the memory session store in 1) immediate and not conditional on locking the session.
This PR also ensures that 4xx or 5xx responses result in warnings, regardless of the enabled logging level.
> Fix chained session deadlock

- server/keyshare/keyshareserver/postgresdb.go
- server/keyshare/keyshareserver/postgresdb_test.go
Now that `user.Secrets` (of type `keysharecore.UserSecrets`) is a slice instead of an array, passing `user.Secrets[:]` to the database query functions means that when they reslice it to be big enough to receive the data, this is not reflected in `user.Secrets`; so it would stay nil.
Regression of 93f79164.
> Fix broken retrieval of keyshare server user from postgres database

- go.mod
- go.sum
- internal/sessiontest/revocation_test.go
- irmaclient/revocation.go
- irmaconfig.go
- revocation.go
- schemes.go
- server/conf.go
- server/irmaserver/api.go
- server/keyshare/keyshareserver/server.go
- server/keyshare/myirmaserver/server.go
The current scheduler library (https://github.com/jasonlvhit/gocron) has been abandoned and causes race conditions (https://github.com/privacybydesign/irmago/issues/57). There is an active fork from the maintainers that inherited the original project, which is an (almost) drop-in replacement: https://github.com/go-co-op/gocron
This PR replaces jasonlvhit/gocron with go-co-op/gocron
> Upgrade cron library to maintained go-co-op/gocron

- irmaclient/client.go
- irmaclient/revocation.go
- server/conf.go
- server/irmaserver/api.go
- server/keyshare/keyshareserver/server.go
- server/keyshare/myirmaserver/server.go
If an `irmaclient.Client` has revocable credentials, then during startup of the client the following two functions are started almost simultaneously in `irmaclient.Client.initRevocation()`:
* [a goroutine](https://github.com/privacybydesign/irmago/blob/master/irmaclient/revocation.go#L27) precomputing for each revocable credential a resource-intensive part of the nonrevocation proof that would be required during disclosure of the credential;
* [a gocron job](https://github.com/privacybydesign/irmago/blob/master/irmaclient/revocation.go#L42) that for each revocable credential fetches fresh revocation state from the issuer if the credential's revocation state is too old. This job is set to runs every 10 seconds, but the first time it runs is immediately when adding it to the scheduler.
Both …
> Avoid gocron panics in revocation code during irmaclient startup

- server/keyshare/myirmaserver/server.go
From: [noreply@sidn.nl](mailto:noreply@sidn.nl)
To: [yivi2@humilis.net](mailto:yivi2@humilis.net)
Subject: /sidn/myirma/mail/account_removed.en.html
Dear IRMA user,
We have received a request to delete your IRMA account (app ID
> Fix: use subject value instead of file path value as subject in account removed mail

- CHANGELOG.md
- server/requestorserver/auth.go
- server/requestorserver/auth_test.go
The `/revocation` endpoint for requestors was not usable using JWT authentication.  
When you tried this an error occured:  
```stacktrace
2022/10/31 13:16:26 http: panic serving 172.18.0.1:61426: interface conversion: jwt.Claims is *irma.RevocationJwt, not *jwt.StandardClaims
goroutine 417 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1850 +0xb8
panic({0x8cb0c0, 0x400040f7d0})
/usr/local/go/src/runtime/panic.go:890 +0x260
net/http.(*timeoutHandler).ServeHTTP(0x40004eb980, {0xb23168, 0x40000f21c0}, 0x40001aa000)
/usr/local/go/src/net/http/server.go:3412 +0x6f8
github.com/privacybydesign/irmago/server.TimeoutMiddleware.func1.1({0xb23168?, 0x40000f21c0?}, 0x1?)
/irmago/server/api.go:491 +0x7c
net/http.HandlerFunc.ServeHTTP(0x4000501480?, {0xb23168?, …
```
> Bugfix: revocation using JWT authentication

- go.mod
- go.sum
- irmaclient/client.go
- irmaclient/keyshare.go
- irmaclient/legacy.go
- irmaclient/session.go
- irmaconfig.go
- requests.go
- server/irmaserver/sessions.go
This version of `gabi` produces a `proofU` that proves knowledge of both keyshares. To take that into account, this commit changes the following:
- `irmaclient.Client.startKeyshareSession()` is now called `newKeyshareSession`, because it does not actually immediately start the session. Instead, it returns after checking the user's PIN. This is necessary because what happens next now differs per session type, see next point.
- In case of disclosure/ABS, the session proceeds as before. In case of issuance, `/api/v2/prove/getPs` at the keyshare server is first invoked to retrieve the `P` values (`R_0^{keyshare server secret}`), after which the session is started.
- In case of the old keyshare protocol, the keyshare's `P` is divided out from the `U` of the `proofU` because that is what the …
> Support gabi with updated keyshare protocol

- irmaconfig.go
- irmago_test.go
- schemes.go
This PR solves issue #139 issue by:
* Include a dot in the tempdirs made by the scheme updating function, i.e. `/path/to/schemes/.tempscheme3581524345`.
* Just before iterating over the schemes within the scheme folder, try to remove any existing `.tempschemeXXXXXXXXXX` folders from `/path/to/schemes`.
* When iterating over the schemes within the scheme folder, skip folders beginning with a dot. (Note that no scheme name can ever contain a dot.)
Fixes #139
> Fix leftover temp folder in scheme folder if scheme updating is aborted

- CHANGELOG.md
- internal/common/common.go
- irmaconfig.go
- irmago_test.go
- version.go
> Fix: ParseFolder cannot handle legacy oldscheme and tempscheme directories

- irma/cmd/config.go
- irma/cmd/server.go
- server/conf.go
- server/irmaserver/sessions.go
Changed default to 15 minutes, while keeping the SessionResult lifetime to 5 minutes.
> Feat: make it possible to increase MaxSessionLifetime without increasing the SessionResult lifetime

- irmaclient/legacy.go
- irmaclient/storage.go
- irmaconfig.go
This feature prevents apps from starting if the scheme directory is a bit messy. By adding some checks in the storage classes, we prevent the app to start when configuration is missing that was in use.
> Feat: ignore directories in irma_configuration directory that don't contain a scheme

- CHANGELOG.md
- README.md
- go.mod
- internal/sessiontest/revocation_test.go
- revocation.go
- revocation_db.go
Besides postgres and mysql, support for mssql is preferrable for our environment.
Mostly to prevent yet another database type to be added to our hosting environment.
Support has only been added for the revocation part, since that is the part we need.
Due to a case-sensitivity bug in the GORM mssql package, there was a need to uppercase some of the GORM instructions.
The [README.md](README.md) has been updated with instructions to run the tests against SQL Server.
We have been running with this configuration for a few months in our staging environment, without any problems.
> add mssql (Microsoft SQL Server) as supported db type for revocation

- CHANGELOG.md
- server/keyshare/email.go
The header gets converted to 'Content-Transfer-Encoding: quoted-printable' causing 'arc=fail (body hash mismatch)' with gmail
> feat: remove mail header 'Content-Transfer-Encoding: binary'

- CHANGELOG.md
- internal/keysharecore/operations_test.go
- server/keyshare/keyshareserver/server.go
The missing tests are #327 and #334. If all PRs are being merged together, then everything is properly tested.
Furthermore, I removed two other TODOs that were merely cosmetic.  It does not really need a follow-up.
> Chore: remove leftover TODOs (new keyshare protocol)

- .github/workflows/status-checks.yml
To prevent that the pipeline stops working when the support is actually removed.
> CI/CD: bump deprecated GitHub Actions dependencies

- CHANGELOG.md
- version.go
Preparing the changelog for release `v0.17.1`.
> chore: Prepare for v0.17.1

- CHANGELOG.md
#408 was merged, but the date in the changelog was copied from a previous release.
> fix date in changelog

- CHANGELOG.md
- irmaclient/keyshare.go
- version.go
The pin challenge for the keyshare server would always be done at least twice.
This commit also releases version 0.18.1.
> Fix pin challenge in irmaclient

- .gitattributes
- internal/sessiontest/helper_servers_test.go
- internal/sessiontest/legacy_test.go
- internal/sessiontest/logs_test.go
- internal/sessiontest/redis_test.go
- internal/sessiontest/session_test.go
- irmaclient/irmaclient_test.go
- schemes.go
- testdata/irma_configuration_updated/.gitignore
- testdata/irma_configuration_updated/test
- testdata/irma_configuration_updated/test2
This pull request introduces several changes aimed at improving test reliability, enhancing cross-platform compatibility, and ensuring proper resource cleanup in the codebase. The most significant changes include the addition of symbolic link setup for tests, proper closing of resources in test cases, and updates to path handling for better compatibility across operating systems.
* Added a new `ensureSymlinks` function in `internal/sessiontest/helper_servers_test.go` to create symbolic links required for certain tests, with cross-platform support for Windows, macOS, and Linux. This function is invoked in `StartIrmaServer` to ensure the necessary setup is in place. [[1]](diffhunk://#diff-68ffaae070a6bbe0623df8506dbf61f5e735898da6762f2c49f987e86f9b35cdR80-R117) …
> Add support for development on Windows
