privacybydesign/irmago

- irmaclient/session_test.go
See: https://github.com/privacybydesign/irma_api_server/pull/11
> Change API server port to 8088

- irma/cmd/session.go
Some code duplication was unavoidable without splitting up `requestorserver.initialize`
> Support --url for session

- server/requestorserver/server.go
It also emits a more specific warning in this case.
> Server checks content-type of request

- internal/sessiontest/session_test.go
- irmaclient/client.go
- irmaclient/irmaclient_test.go
- irmaclient/storage.go
This pull requests adds a remove-all function to the client which removes:
- All attributes
- All (CL) signatures
- All user data: secret key, keyshare servers, preferences and updates
- All logs
After this, a new secret key is generated.
> Complete storage removal

- CHANGELOG.md
- messages.go
- server/irmaserver/api.go
A suggestion on how to indicate in QRs that pairing is recommended to be enabled.
> Introduce PairingRecommended field in Qr

- internal/sessiontest/main_test.go
- irmaclient/client.go
- irmaclient/irmaclient_test.go
- irmaconfig.go
- schemes.go
> fix: fallback if os.Rename() fails

- internal/sessiontest/main_test.go
- internal/sessiontest/session_test.go
- requests.go
- server/api.go
- server/api_test.go
- server/irmaserver/helpers_test.go
> Fix exp date for default disclosure request

- irma/cmd/server.go
- server/conf.go
- server/requestorserver/server.go
> Add flag to IRMA server allowing callbackUrl in session requests without JWT private key installed

- descriptions.go
> Add Unverified field to RequestorInfo to indicate the name cannot be trusted

- irma/cmd/server.go
- requests.go
- server/conf.go
- server/irmaserver/helpers.go
- server/irmaserver/sessions.go
This makes it easier to implement stateless servers using irma sessions
> Added option to augment clientreturnurl with server session token.

- server/irmaserver/handle.go
The presence of a next session URL in the session status message informs the frontend that there is a next session, so that it should not yet tell the user the session has finished. Previously the session status was set to DONE before the next session URL was retrieved. When SSE is used and the session status changes, the frontend is notified of this almost immediately. Thus in this case, it did not receive the next session URL, considering the session (chain) finished.
> Fix SSE in combination with chained sessions

- Dockerfile
- README.md
- docker-compose.yml
Hi,
I wanted to run IRMA server in our Kubernetes cluster and was in need of a docker image. I can imagine others would like this too.
Not sure if there is a reason this was not yet there?
I also have code for the gitlab-ci file which creates a docker image and adds it to the gitlab containers repository if you are interested.
> [IRMA] Add Dockerfile for irma server

- transport.go
For `irmamobile` we need `irmago` to use additional root certificates, besides the ones loaded in the system. In the current setup, irmamobile would need to write the certificates from memory to disk, such that irmago can load them from the location specified by the environment variable `SSL_CERT_DIR`. This creates superfluous overhead.
Therefore, it would be nice to have support to immediately include the certificates in Go. Then we don't need to write them to disk first.
> Feat: added option to specify which TLS configuration to use for outbound connections

- irma/cmd/keyshare-myirma.go
- irma/cmd/keyshare-server.go
- irma/cmd/keyshare-tasks.go
- server/keyshare/keyshareserver/conf.go
- server/keyshare/keyshareserver/postgresdb.go
- server/keyshare/keyshareserver/postgresdb_test.go
- server/keyshare/myirmaserver/conf.go
- server/keyshare/myirmaserver/postgresdb.go
- server/keyshare/myirmaserver/postgresdb_test.go
> Feat: make postgresdb connection bounds configurable

- server/errors.go
- server/keyshare/keyshareserver/postgresdb.go
- server/keyshare/keyshareserver/postgresdb_test.go
- server/keyshare/keyshareserver/server.go
- server/keyshare/myirmaserver/postgresdb.go
- server/keyshare/myirmaserver/postgresdb_test.go
- server/keyshare/myirmaserver/server.go
- server/keyshare/myirmaserver/server_email_test.go
Fixes medium security issue in myirmaserver. Server is not live yet, so it is not an active vulnerability.
> Fix: prevent enumeration attack on email addresses and added rate limiting for emails

- internal/test/testdata.go
- revocation.go
> Fix race conditions in revocation code

- internal/common/common.go
- internal/keysharecore/testuser_test.go
- internal/sessiontest/helper_dosession_test.go
- internal/sessiontest/session_test.go
- internal/test/postgres.go
- internal/test/testdata.go
- irma/cmd/keygen.go
- irma/cmd/keyshare-keygen.go
- irma/cmd/sign.go
- irma/cmd/update.go
- irmaclient/irmaclient_test.go
- irmaclient/legacy.go
- irmaconfig.go
- irmago_test.go
- keyring.go
- requests.go
- schemes.go
- server/api.go
- server/keyshare/keyshareserver/conf.go
- transport.go
To resolve feedback in PR #299
> Refactor: phase out deprecated io/ioutil library

- CHANGELOG.md
- internal/sessiontest/helper_servers_test.go
- internal/sessiontest/redis_test.go
- internal/sessiontest/session_test.go
- requests.go
- server/irmaserver/api.go
- server/irmaserver/helpers.go
- server/requestorserver/conf.go
- server/requestorserver/server.go
Check https://github.com/privacybydesign/irma-documentation/pull/54 for the documentation.
> Feat: option to overrule host name in IRMA QR

- irmaclient/client.go
- irmaclient/helpers.go
- irmaclient/irmaclient.go
- irmaclient/openid4vpclient.go
- irmaclient/session.go
Is required when you have to do an issuance flow during a disclosure session. 
Relates to https://github.com/privacybydesign/irmamobile/issues/357
> Add ability to refresh verification permission request for OpenID4VP after IRMA issuance session

- descriptions.go
- eudi/eudiconfig.go
- internal/sessiontest/ios_logo_path_bug_test.go
- irmaclient/client.go
- irmaclient/openid4vpclient.go
- schemes.go
Fixes https://github.com/privacybydesign/irmamobile/issues/374
> Fix iOS log image bug
